### ISSUE TITLE
Mention GNU Readline dependency in the Readme.md

### ISSUE THREAD

**Issue by Lawyar** [yellow-footed-honeyguide/uc#1]
I've tried to build uc on the Ubuntu 22.10 system and got error `Readline library not found!`:  
```
mkdir build && cd build && cmake .. && make
-- The C compiler identification is GNU 12.2.0
-- The CXX compiler identification is GNU 12.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:15 (message):
  Readline library not found!
```  
This error means that uc project depends on readline library but it wasn't installed on my computer.  
There is a sentence in the dependencies chapter:  
> This utility is a robust, pure C implementation, crafted from scratch without external libraries for seamless, efficient performance.   

Thus, documentation should be improved to mention this dependency.

**Comment by yellow-footed-honeyguide** [comment]
@Lawyar , thank you! Fixed
